In [1]:
import numpy as np 
import pandas as pd
import tensorflow as tf

# Importing Dataset 

In [2]:
data=pd.read_csv("C:\\Users\\SAMA\\Downloads\\American-Express-dataset - Sheet1.csv")
data

Credit Score  Geography  Gender  Age  Customer Since  Current Account  \
0              553      Delhi  Female   45               4     0.000000e+00   
1              447  Bengaluru    Male   31               7     0.000000e+00   
2              501      Delhi  Female   32               2     0.000000e+00   
3              428      Delhi    Male   51               3     0.000000e+00   
4              492      Delhi  Female   57               6     1.912682e+06   
...            ...        ...     ...  ...             ...              ...   
7317           510      Delhi    Male   70               5     0.000000e+00   
7318           475     Mumbai    Male   32               7     1.396908e+06   
7319           624  Bengaluru    Male   38               7     0.000000e+00   
7320           557      Delhi    Male   24               8     8.910724e+05   
7321           417  Bengaluru    Male   42               1     0.000000e+00   

      Num of products  UPI Enabled  Estimated Yearly Income  Closed  
0                   4            1                   274150       0  
1                   4            1                   519360       0  
2                   4            1                   545501       0  
3                   4            1                    86868       0  
4                   2            1                   518680       0  
...               ...          ...                      ...     ...  
7317                2            0                   251912       1  
7318                2            1                   487067       1  
7319                4            1                   259649       0  
7320                2            0                   538583       0  
7321                4            0                   427703       0  

[7322 rows x 10 columns]

In [3]:
x=data.iloc[:,0:9].values
y=data.iloc[:,-1].values
print(x)
print()
print(y)

[[553 'Delhi' 'Female' ... 4 1 274150]
 [447 'Bengaluru' 'Male' ... 4 1 519360]
 [501 'Delhi' 'Female' ... 4 1 545501]
 ...
 [624 'Bengaluru' 'Male' ... 4 1 259649]
 [557 'Delhi' 'Male' ... 2 0 538583]
 [417 'Bengaluru' 'Male' ... 4 0 427703]]

[0 0 0 ... 0 0 0]


# Apply Label and One hot encoding

In [31]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])
print(x)

[[0.0 1.0 0 ... 4 1 274150]
 [1.0 0.0 1 ... 4 1 519360]
 [0.0 1.0 0 ... 4 1 545501]
 ...
 [1.0 0.0 1 ... 4 1 259649]
 [0.0 1.0 0 ... 2 0 538583]
 [1.0 0.0 1 ... 4 0 427703]]


# Apply One Hot Encoder 

In [101]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
x=np.array(ct.fit_transform(x))
le_y = LabelEncoder()
y = np.array(le_y.fit_transform(y))
print(y)
print(x)


[0 0 0 ... 0 0 0]
[[0.0 1.0 0.0 ... 4 1 274150]
 [1.0 0.0 1.0 ... 4 1 519360]
 [0.0 1.0 0.0 ... 4 1 545501]
 ...
 [1.0 0.0 1.0 ... 4 1 259649]
 [0.0 1.0 0.0 ... 2 0 538583]
 [1.0 0.0 1.0 ... 4 0 427703]]


In [103]:
print(np.unique(y_train))
print(y_train[:10])


[0 1]
[0 0 0 1 0 0 1 1 0 1]


# Split data to train and test 

In [111]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

print((y_train).shape)
print((x_train).shape)

(5857,)
(5857, 14)


# Feature Scaling of data 

In [112]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

# Artificial Neural Networks (ANN)

# Intialaisation

In [113]:
# Initialize a Sequential model from Keras
# Sequential models are linear stacks of layers where you can add one layer at a time
ann = tf.keras.models.Sequential()

# Adding Input Layer and First hidden layer 

In [114]:
# Add a hidden layer to the neural network with 5 neurons and ReLU activation function
ann.add(tf.keras.layers.Dense(units=5,activation='relu'))

# Adding Second hidden layer 

In [115]:
# Add a hidden layer to the neural network with 5 neurons (units)
# and ReLU activation function for introducing non-linearity
#Now we will have a input layer 2 hidden, layer 1 hidden layer is created at time of creting input layer
ann.add(tf.keras.layers.Dense(units=5,activation='relu'))

# Adding Output layer

In [116]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

# ANN Training 

# Compiling ANN

In [117]:
# there are diff optimisers in keras which do complex methods to improve performance 
# 'adam' optimizer: An efficient stochastic gradient descent algorithm that adapts learning rates
# 'binary_crossentropy': Loss function ideal for binary classification problems
# 'accuracy': Metric to monitor the percentage of correctly classified samples during training
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

# Training on Dataset 

In [118]:
ann.fit(x_train,y_train,epochs=120,batch_size=32)

Epoch 1/120
184/184 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.6280 - loss: 0.6811
Epoch 2/120
184/184 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.7736 - loss: 0.5468
Epoch 3/120
184/184 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.7885 - loss: 0.5088  
Epoch 4/120
184/184 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.7893 - loss: 0.4862  
Epoch 5/120
184/184 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.7893 - loss: 0.4711
Epoch 6/120
184/184 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.7893 - loss: 0.4615
Epoch 7/120
184/184 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7893 - loss: 0.4545  
Epoch 8/120
184/184 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.7890 - loss: 0.4496  
Epoch 9/120
184/184 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7905 - loss: 0.4454  
Epoch 10/120
184/184 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7915 - loss: 0.4422  
Epoch 11/120
184/184 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7924 - loss: 0.4390  
Epoch 12/120
184/184 ━━━━━━

# Confusion matrix and Accuracy score

In [120]:
from sklearn.metrics import accuracy_score,confusion_matrix
y_pred=ann.predict(x_test)
y_pred=(y_pred>0.5)
cm=confusion_matrix(y_test,y_pred)
ac=accuracy_score(y_test,y_pred)
print(cm)
print(ac)

46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step 
[[1087   79]
 [ 170  129]]
0.8300341296928327
