<a href="https://colab.research.google.com/github/neelima-singh07/Machine-Learning-/blob/main/Descion_Tree_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data=pd.read_excel('/content/regression sheet.xlsx')
data

Age  Mobile Phone  Purchased
0     15          6334          0
1     28          6667          0
2     20         14334          0
3     21         19000          0
4     15         25334          0
..   ...           ...        ...
194   28         26334          0
195   34         43000          1
196   42         11334          1
197   37         16667          1
198   33         26334          0

[199 rows x 3 columns]

In [3]:
x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values
print(x)
print()
print(y)

[[   15  6334]
 [   28  6667]
 [   20 14334]
 [   21 19000]
 [   15 25334]
 [   21 19334]
 [   21 28000]
 [   25 50000]
 [   20 11000]
 [   28 21667]
 [   20 26667]
 [   26 17000]
 [   28 36000]
 [   18  6667]
 [   20 26334]
 [   21 18000]
 [   24 45000]
 [   24 29667]
 [   19 10667]
 [   14 14667]
 [   23 27667]
 [   28  7667]
 [   21 19334]
 [   19 18334]
 [   18 16000]
 [   22 26334]
 [   17  6000]
 [   25 39000]
 [   21  6667]
 [   20 29000]
 [   18 22000]
 [   25 40000]
 [   17 21000]
 [   24 22667]
 [   20 26667]
 [   19  9000]
 [   16  7667]
 [   26 37667]
 [   25  6000]
 [   27 37334]
 [   24 38667]
 [   20  5000]
 [   23  9334]
 [   23 27667]
 [   26 49667]
 [   15  7000]
 [   16 24000]
 [   20 11667]
 [   21 29667]
 [   20 28667]
 [   30 26667]
 [   31 23667]
 [   29 23667]
 [   20 30000]
 [   29 11000]
 [   17 18334]
 [   28 23667]
 [   23 49334]
 [   23 15667]
 [   16 29334]
 [   27 38334]
 [   20 39334]
 [   27 14334]
 [   27 24000]
 [   18  9334]
 [   28 15667]
 [   20  7

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2)
print(x_train)
print()
print(x_test)

[[   32 17334]
 [   25  6000]
 [   18 16000]
 [   34 44334]
 [   32 20334]
 [   20 29000]
 [   14 14667]
 [   38 24667]
 [   29 17334]
 [   30 19667]
 [   28 23667]
 [   21 19334]
 [   28 16667]
 [   36 26334]
 [   28 19334]
 [   32 25000]
 [   48 36000]
 [   32 20000]
 [   42 11334]
 [   36 39000]
 [   37 48000]
 [   25 40000]
 [   28 36000]
 [   19  9000]
 [   36 27334]
 [   23  9334]
 [   23 14334]
 [   28 24000]
 [   28 48000]
 [   31 23667]
 [   28 20000]
 [   29 26000]
 [   20  5000]
 [   29 26667]
 [   33 26667]
 [   17  6000]
 [   32 19000]
 [   32 26000]
 [   29 25667]
 [   20 14334]
 [   24 26334]
 [   16 24000]
 [   39 28667]
 [   38 43667]
 [   33 36000]
 [   16  7667]
 [   20 39334]
 [   21 19334]
 [   31 44667]
 [   36 32000]
 [   24 22667]
 [   26 17000]
 [   28 18000]
 [   29 20667]
 [   21 28000]
 [   25 39000]
 [   32 24000]
 [   15 25334]
 [   17 21000]
 [   32 26667]
 [   48 14000]
 [   28 26334]
 [   47 25334]
 [   20 26667]
 [   27 14334]
 [   33 49667]
 [   31 35

In [7]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [8]:
#train dataset on model descion tree classifier
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier(criterion='entropy',random_state=0)
classifier.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [13]:
classifier.predict(np.array([21,19087]).reshape(1,-1))

array([1])

In [12]:
#acuuracy score and confusion matrix
from sklearn.metrics import confusion_matrix,accuracy_score
y_pred=classifier.predict(x_test)
cm=confusion_matrix(y_test,y_pred)
score=accuracy_score(y_test,y_pred)
print(cm)
print(score)

[[18  7]
 [ 5 10]]
0.7


In [16]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))


[[1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 0]
 [1 0]
 [0 1]
 [1 1]
 [0 0]
 [1 0]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]]


In [17]:
#confusion matrix and accuracy score
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[18  7]
 [ 5 10]]


0.7