<a href="https://colab.research.google.com/github/neelima-singh07/Machine-Learning-/blob/main/KNN_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Import dataset

In [2]:
data=pd.read_excel('/content/dataset-creditScore.xlsx')
data

Existing Loans  Credit Score  Loan Given
0                 0            84           0
1                 0           100           0
2                 0           100           0
3                 0           106           0
4                 0           112           0
..              ...           ...         ...
221               3           892           0
222               3           892           0
223               2           894           1
224               2           896           1
225               3           900           0

[226 rows x 3 columns]

In [3]:
x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values
print(x)
print()
print(y)

[[  0  84]
 [  0 100]
 [  0 100]
 [  0 106]
 [  0 112]
 [  0 112]
 [  0 112]
 [  0 117]
 [  0 117]
 [  0 123]
 [  0 123]
 [  0 123]
 [  0 128]
 [  0 128]
 [  0 128]
 [  0 145]
 [  0 145]
 [  0 150]
 [  0 156]
 [  0 156]
 [  0 167]
 [  0 178]
 [  0 178]
 [  0 178]
 [  0 184]
 [  0 184]
 [  0 189]
 [  0 195]
 [  0 200]
 [  0 200]
 [  0 212]
 [  0 217]
 [  0 217]
 [  0 217]
 [  0 228]
 [  0 234]
 [  0 234]
 [  0 239]
 [  0 239]
 [  0 239]
 [  0 239]
 [  0 239]
 [  0 245]
 [  0 262]
 [  0 262]
 [  0 262]
 [  0 267]
 [  0 278]
 [  0 278]
 [  0 278]
 [  0 284]
 [  0 284]
 [  0 289]
 [  0 289]
 [  0 289]
 [  0 295]
 [  0 300]
 [  0 300]
 [  0 306]
 [  0 306]
 [  0 306]
 [  0 317]
 [  0 317]
 [  0 323]
 [  0 323]
 [  0 323]
 [  0 328]
 [  0 334]
 [  0 334]
 [  0 334]
 [  0 334]
 [  1 339]
 [  0 339]
 [  1 345]
 [  0 350]
 [  1 350]
 [  0 362]
 [  0 362]
 [  0 362]
 [  1 362]
 [  1 367]
 [  0 378]
 [  0 389]
 [  0 389]
 [  0 395]
 [  0 395]
 [  0 395]
 [  0 395]
 [  0 395]
 [  0 400]
 [  0 400]

# splitting dataset to train and test

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train)
print()
print(x_test)

[[  0 334]
 [  0 295]
 [  0 445]
 [  0 456]
 [  1 860]
 [  0 395]
 [  0 400]
 [  0 406]
 [  0 439]
 [  0 239]
 [  0 184]
 [  0 445]
 [  2 750]
 [  2 812]
 [  0 123]
 [  0 334]
 [  0 200]
 [  0 156]
 [  0 434]
 [  0 328]
 [  1 345]
 [  0 112]
 [  0 300]
 [  0 439]
 [  1 489]
 [  1 489]
 [  0 323]
 [  1 495]
 [  1 795]
 [  2 896]
 [  0 217]
 [  0 128]
 [  0 234]
 [  0 200]
 [  0 245]
 [  0 456]
 [  0 439]
 [  2 567]
 [  0 284]
 [  1 745]
 [  1 745]
 [  0 362]
 [  0 239]
 [  0 400]
 [  0 489]
 [  0 362]
 [  2 589]
 [  0 189]
 [  2 845]
 [  1 795]
 [  0 456]
 [  0  84]
 [  0 100]
 [  0 362]
 [  0 267]
 [  0 412]
 [  0 439]
 [  0 489]
 [  1 628]
 [  0 400]
 [  0 395]
 [  0 600]
 [  1 534]
 [  0 407]
 [  0 234]
 [  0 478]
 [  0 317]
 [  0 178]
 [  0 517]
 [  2 600]
 [  0 217]
 [  0 123]
 [  2 892]
 [  1 728]
 [  0 112]
 [  0 195]
 [  1 495]
 [  3 890]
 [  2 890]
 [  0 578]
 [  0 112]
 [  0 445]
 [  0 217]
 [  0 623]
 [  0 317]
 [  0 462]
 [  2 867]
 [  0 662]
 [  0 334]
 [  0 700]
 [  0 323]

# Feature scaling

In [5]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)
print(x_train)
print()
print(x_test)


[[-0.55891365 -0.54570412]
 [-0.55891365 -0.71475415]
 [-0.55891365 -0.0645617 ]
 [-0.55891365 -0.01688092]
 [ 0.73088709  1.73430408]
 [-0.55891365 -0.28129252]
 [-0.55891365 -0.25961944]
 [-0.55891365 -0.23361174]
 [-0.55891365 -0.0905694 ]
 [-0.55891365 -0.95749267]
 [-0.55891365 -1.19589657]
 [-0.55891365 -0.0645617 ]
 [ 2.02068783  1.25749628]
 [ 2.02068783  1.5262425 ]
 [-0.55891365 -1.46030817]
 [-0.55891365 -0.54570412]
 [-0.55891365 -1.12654271]
 [-0.55891365 -1.31726583]
 [-0.55891365 -0.11224248]
 [-0.55891365 -0.57171182]
 [ 0.73088709 -0.49802334]
 [-0.55891365 -1.50798895]
 [-0.55891365 -0.69308107]
 [-0.55891365 -0.0905694 ]
 [ 0.73088709  0.12616142]
 [ 0.73088709  0.12616142]
 [-0.55891365 -0.5933849 ]
 [ 0.73088709  0.15216912]
 [ 0.73088709  1.45255402]
 [ 2.02068783  1.89035027]
 [-0.55891365 -1.05285423]
 [-0.55891365 -1.43863509]
 [-0.55891365 -0.97916575]
 [-0.55891365 -1.12654271]
 [-0.55891365 -0.93148497]
 [-0.55891365 -0.01688092]
 [-0.55891365 -0.0905694 ]
 

# Apply KNN model


In [7]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
classifier.fit(x_train,y_train)

KNeighborsClassifier()

# Predicting

In [18]:
print(classifier.predict(sc.transform(np.array([1,730]).reshape(1, -1))))
print(classifier.predict(sc.transform(np.array([2,730]).reshape(1, -1))))

[1]
[0]


# Confusion matrix and accuracy score

In [19]:
from sklearn.metrics import confusion_matrix,accuracy_score
y_pred=classifier.predict(x_test)
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)
#91%accuracy

[[21  2]
 [ 2 21]]


0.9130434782608695