<a href="https://colab.research.google.com/github/neelima-singh07/Machine-Learning-/blob/main/Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# Importing dataset

In [3]:
data=pd.read_excel('/content/regression sheet.xlsx')
data

Age  Mobile Phone  Purchased
0     15          6334          0
1     28          6667          0
2     20         14334          0
3     21         19000          0
4     15         25334          0
..   ...           ...        ...
194   28         26334          0
195   34         43000          1
196   42         11334          1
197   37         16667          1
198   33         26334          0

[199 rows x 3 columns]

# splitting dataset

In [15]:
from sklearn.model_selection import train_test_split
x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values


In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train)
print()
print(x_test)

[[   32 17334]
 [   25  6000]
 [   18 16000]
 [   34 44334]
 [   32 20334]
 [   20 29000]
 [   14 14667]
 [   38 24667]
 [   29 17334]
 [   30 19667]
 [   28 23667]
 [   21 19334]
 [   28 16667]
 [   36 26334]
 [   28 19334]
 [   32 25000]
 [   48 36000]
 [   32 20000]
 [   42 11334]
 [   36 39000]
 [   37 48000]
 [   25 40000]
 [   28 36000]
 [   19  9000]
 [   36 27334]
 [   23  9334]
 [   23 14334]
 [   28 24000]
 [   28 48000]
 [   31 23667]
 [   28 20000]
 [   29 26000]
 [   20  5000]
 [   29 26667]
 [   33 26667]
 [   17  6000]
 [   32 19000]
 [   32 26000]
 [   29 25667]
 [   20 14334]
 [   24 26334]
 [   16 24000]
 [   39 28667]
 [   38 43667]
 [   33 36000]
 [   16  7667]
 [   20 39334]
 [   21 19334]
 [   31 44667]
 [   36 32000]
 [   24 22667]
 [   26 17000]
 [   28 18000]
 [   29 20667]
 [   21 28000]
 [   25 39000]
 [   32 24000]
 [   15 25334]
 [   17 21000]
 [   32 26667]
 [   48 14000]
 [   28 26334]
 [   47 25334]
 [   20 26667]
 [   27 14334]
 [   33 49667]
 [   31 35

In [7]:
print(y_test)

[0 1 1 1 1 0 0 0 0 0 0 0 1 1 0 1 0 1 0 0 1 1 0 0 0 0 0 1 0 1 1 0 1 1 0 0 1
 0 1 0]


# Feature scaling

In [18]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)
print(x_train)


[[ 0.30645937 -0.72727353]
 [-0.55054887 -1.66795146]
 [-1.40755711 -0.83799034]
 [ 0.55131887  1.5136215 ]
 [ 0.30645937 -0.47828519]
 [-1.16269761  0.24095912]
 [-1.8972761  -0.94862416]
 [ 1.04103786 -0.11866304]
 [-0.06082987 -0.72727353]
 [ 0.06159987 -0.5336436 ]
 [-0.18325962 -0.20165915]
 [-1.04026786 -0.56128131]
 [-0.18325962 -0.78263194]
 [ 0.79617836  0.01969148]
 [-0.18325962 -0.56128131]
 [ 0.30645937 -0.09102533]
 [ 2.26533534  0.8219319 ]
 [ 0.30645937 -0.50600589]
 [ 1.53075685 -1.2252502 ]
 [ 0.79617836  1.07092024]
 [ 0.91860811  1.81788525]
 [-0.55054887  1.15391635]
 [-0.18325962  0.8219319 ]
 [-1.28512736 -1.41896313]
 [ 0.79617836  0.10268759]
 [-0.79540836 -1.39124243]
 [-0.79540836 -0.97626187]
 [-0.18325962 -0.17402145]
 [-0.18325962  1.81788525]
 [ 0.18402962 -0.20165915]
 [-0.18325962 -0.50600589]
 [-0.06082987 -0.00802922]
 [-1.16269761 -1.75094758]
 [-0.06082987  0.04732919]
 [ 0.42888912  0.04732919]
 [-1.52998685 -1.66795146]
 [ 0.30645937 -0.58900201]
 

In [19]:
print(y_test)

[0 0 0 1 0 1 0 0 1 0 1 0 0 0 0 1 0 0 0 1 1 0 0 1 0 1 1 0 0 1 0 0 1 1 1 0 0
 1 0 0]


# Applying Logigistic regx


In [20]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression (random_state=42)
classifier.fit(x_train,y_train)


LogisticRegression(random_state=42)

# Predicting

In [34]:
classifier.predict([[15,26678]])

array([1])

In [35]:
# Try predicting with different values for Age and Mobile Phone Price
new_prediction = classifier.predict([[40, 80000]]) # Example: Age 40, Mobile Phone Price 80000
print(new_prediction)

[1]


In [38]:
# Predict with a younger age and lower mobile phone price
new_prediction_low_values = classifier.predict([[28, 1000]]) # Example: Age 20, Mobile Phone Price 10000
print(new_prediction_low_values)

[1]


In [42]:
#confusion matrix
from sklearn.metrics import confusion_matrix,accuracy_score
y_pred=classifier.predict(x_test)
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)




[[23  2]
 [ 3 12]]


0.875