<a href="https://colab.research.google.com/github/neelima-singh07/Machine-Learning-/blob/main/Unstop_PreProcessing_of_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#by neelima :)

# Importing Libraries and Dataset


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
data=pd.read_excel("//content//Covid_Data_new.xlsx")
data

age body_temperature chronic_disease breathing_issue  \
0   10.0           Normal              no              no   
1   12.0           Normal              no              no   
2   15.0           Normal              no              no   
3   10.0           Normal              no              no   
4   13.0         Moderate              no              no   
..   ...              ...             ...             ...   
65  86.0             High              no             yes   
66  61.0         Moderate              no             yes   
67  94.0             High             yes             yes   
68  81.0             High             yes             yes   
69  76.0             High             yes             yes   

    Blood O2 Level in Percentage Needed Hospitalization  
0                           97.0                     No  
1                           97.0                     No  
2                           94.0                     No  
3                           97.0                     No  
4                           94.0                     No  
..                           ...                    ...  
65                          76.0                    Yes  
66                          90.0                     No  
67                          64.0                    Yes  
68                          75.0                    Yes  
69                          80.0                    Yes  

[70 rows x 6 columns]

In [ ]:
X=data.iloc[:,:-1].values #returns array
Y=data.iloc[:,-1].values
print(X)

[[10.0 'Normal' 'no' 'no' 97.0]
 [12.0 'Normal' 'no' 'no' 97.0]
 [15.0 'Normal' 'no' 'no' 94.0]
 [10.0 'Normal' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 94.0]
 [12.0 'Moderate' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 93.0]
 [15.0 'Moderate' 'no' 'no' 92.0]
 [18.0 'Moderate' 'no' 'no' 66.0]
 [19.0 'Normal' 'no' 'no' 92.0]
 [20.0 'Normal' 'no' 'no' 93.0]
 [17.0 'Normal' 'no' 'no' 93.0]
 [16.0 'Normal' 'no' 'no' 92.0]
 [18.0 'Normal' 'no' 'no' 93.0]
 [20.0 'Normal' 'no' 'no' 92.0]
 [25.0 'Moderate' 'no' 'no' 93.0]
 [24.0 'Moderate' 'no' 'no' 92.0]
 [26.0 'High' 'no' 'no' 94.0]
 [28.0 'Normal' 'no' 'no' 99.0]
 [29.0 'Normal' 'no' 'no' 93.0]
 [30.0 'Moderate' 'no' 'no' 62.0]
 [19.0 'Normal' 'no' 'no' 89.0]
 [25.0 'Normal' 'no' 'yes' 86.0]
 [26.0 'Normal' 'no' 'no' nan]
 [28.0 'Normal' 'no' 'no' 89.0]
 [30.0 'Moderate' 'yes' 'no' 86.0]
 [35.0 'Moderate' 'no' 'no' 89.0]
 [32.0 'Moderate' 'no' 'yes' 84.0]
 [nan 'Moderate' 'yes' 'no' 90.0]
 [32.0 'Moderate' 'no' 'no' 89.0]
 [35.0 'Modera

In [ ]:
data.isnull().sum()

age                             1
body_temperature                0
chronic_disease                 0
breathing_issue                 0
Blood O2 Level in Percentage    1
Needed Hospitalization          0
dtype: int64

In [ ]:
data

age body_temperature chronic_disease breathing_issue  \
0   10.0           Normal              no              no   
1   12.0           Normal              no              no   
2   15.0           Normal              no              no   
3   10.0           Normal              no              no   
4   13.0         Moderate              no              no   
..   ...              ...             ...             ...   
65  86.0             High              no             yes   
66  61.0         Moderate              no             yes   
67  94.0             High             yes             yes   
68  81.0             High             yes             yes   
69  76.0             High             yes             yes   

    Blood O2 Level in Percentage Needed Hospitalization  
0                           97.0                     No  
1                           97.0                     No  
2                           94.0                     No  
3                           97.0                     No  
4                           94.0                     No  
..                           ...                    ...  
65                          76.0                    Yes  
66                          90.0                     No  
67                          64.0                    Yes  
68                          75.0                    Yes  
69                          80.0                    Yes  

[70 rows x 6 columns]

# Handling Missing data

In [ ]:
from  sklearn.impute import SimpleImputer #import library
imputer=SimpleImputer(missing_values=np.nan,strategy='mean') #use simple imp to replace nan values by mean

# Apply imputer to the 'age' column (index 3 in the transformed X)
imputer.fit(X[:,3:4])
X[:,3:4]=imputer.transform(X[:,3:4])

# Apply imputer to the 'Blood O2 Level in Percentage' column (index 6 in the transformed X)
imputer.fit(X[:,6:7])
X[:,6:7]=imputer.transform(X[:,6:7])

print(X)

[[0.0 0.0 1.0 10.0 'no' 'no' 97.0]
 [0.0 0.0 1.0 12.0 'no' 'no' 97.0]
 [0.0 0.0 1.0 15.0 'no' 'no' 94.0]
 [0.0 0.0 1.0 10.0 'no' 'no' 97.0]
 [0.0 1.0 0.0 13.0 'no' 'no' 94.0]
 [0.0 1.0 0.0 12.0 'no' 'no' 97.0]
 [0.0 1.0 0.0 13.0 'no' 'no' 93.0]
 [0.0 1.0 0.0 15.0 'no' 'no' 92.0]
 [0.0 1.0 0.0 18.0 'no' 'no' 66.0]
 [0.0 0.0 1.0 19.0 'no' 'no' 92.0]
 [0.0 0.0 1.0 20.0 'no' 'no' 93.0]
 [0.0 0.0 1.0 17.0 'no' 'no' 93.0]
 [0.0 0.0 1.0 16.0 'no' 'no' 92.0]
 [0.0 0.0 1.0 18.0 'no' 'no' 93.0]
 [0.0 0.0 1.0 20.0 'no' 'no' 92.0]
 [0.0 1.0 0.0 25.0 'no' 'no' 93.0]
 [0.0 1.0 0.0 24.0 'no' 'no' 92.0]
 [1.0 0.0 0.0 26.0 'no' 'no' 94.0]
 [0.0 0.0 1.0 28.0 'no' 'no' 99.0]
 [0.0 0.0 1.0 29.0 'no' 'no' 93.0]
 [0.0 1.0 0.0 30.0 'no' 'no' 62.0]
 [0.0 0.0 1.0 19.0 'no' 'no' 89.0]
 [0.0 0.0 1.0 25.0 'no' 'yes' 86.0]
 [0.0 0.0 1.0 26.0 'no' 'no' 82.07246376811594]
 [0.0 0.0 1.0 28.0 'no' 'no' 89.0]
 [0.0 1.0 0.0 30.0 'yes' 'no' 86.0]
 [0.0 1.0 0.0 35.0 'no' 'no' 89.0]
 [0.0 1.0 0.0 32.0 'no' 'yes' 84.0]
 [0.

# Encoding Categorical data

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [ ]:
#for independent variable
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1]),
                                     ('encoder2', OneHotEncoder(), [4, 5])],
                       remainder='passthrough')
X = np.array(ct.fit_transform(X))
X

array([[1.0, 0.0, 0.0, 1.0, 10.0, 'no', 'no', 97.0],
       [1.0, 0.0, 0.0, 1.0, 12.0, 'no', 'no', 97.0],
       [1.0, 0.0, 0.0, 1.0, 15.0, 'no', 'no', 94.0],
       [1.0, 0.0, 0.0, 1.0, 10.0, 'no', 'no', 97.0],
       [0.0, 1.0, 0.0, 0.0, 13.0, 'no', 'no', 94.0],
       [0.0, 1.0, 0.0, 0.0, 12.0, 'no', 'no', 97.0],
       [0.0, 1.0, 0.0, 0.0, 13.0, 'no', 'no', 93.0],
       [0.0, 1.0, 0.0, 0.0, 15.0, 'no', 'no', 92.0],
       [0.0, 1.0, 0.0, 0.0, 18.0, 'no', 'no', 66.0],
       [1.0, 0.0, 0.0, 1.0, 19.0, 'no', 'no', 92.0],
       [1.0, 0.0, 0.0, 1.0, 20.0, 'no', 'no', 93.0],
       [1.0, 0.0, 0.0, 1.0, 17.0, 'no', 'no', 93.0],
       [1.0, 0.0, 0.0, 1.0, 16.0, 'no', 'no', 92.0],
       [1.0, 0.0, 0.0, 1.0, 18.0, 'no', 'no', 93.0],
       [1.0, 0.0, 0.0, 1.0, 20.0, 'no', 'no', 92.0],
       [0.0, 1.0, 0.0, 0.0, 25.0, 'no', 'no', 93.0],
       [0.0, 1.0, 0.0, 0.0, 24.0, 'no', 'no', 92.0],
       [1.0, 0.0, 1.0, 0.0, 26.0, 'no', 'no', 94.0],
       [1.0, 0.0, 0.0, 1.0, 28.0, 'no', 'no', 

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
Y=le.fit_transform(Y)
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1])

# Seprating Training and Testing data

In [ ]:
from sklearn.model_selection import  train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [ ]:
print(X_test)

[[0.0 0.0 1.0 25.0 'no' 'yes' 86.0]
 [0.0 0.0 1.0 10.0 'no' 'no' 97.0]
 [1.0 0.0 0.0 68.0 'yes' 'no' 67.0]
 [0.0 1.0 0.0 13.0 'no' 'no' 94.0]
 [1.0 0.0 0.0 59.0 'yes' 'no' 68.0]
 [0.0 0.0 1.0 28.0 'no' 'no' 99.0]
 [0.0 0.0 1.0 20.0 'no' 'no' 93.0]
 [1.0 0.0 0.0 46.0 'yes' 'no' 91.0]
 [1.0 0.0 0.0 53.0 'yes' 'no' 55.0]
 [0.0 0.0 1.0 16.0 'no' 'no' 92.0]
 [1.0 0.0 0.0 38.0 'no' 'no' 75.0]
 [0.0 0.0 1.0 19.0 'no' 'no' 92.0]
 [1.0 0.0 0.0 94.0 'yes' 'yes' 64.0]
 [0.0 1.0 0.0 12.0 'no' 'no' 97.0]]


In [ ]:
print(Y_test)

[0 0 1 0 1 0 0 0 1 0 1 0 1 0]


In [ ]:
print(X_train)

[[1.0 0.0 0.0 86.0 'yes' 'yes' 71.0]
 [0.0 1.0 0.0 35.0 'no' 'yes' 92.0]
 [1.0 0.0 0.0 75.0 'no' 'yes' 72.0]
 [1.0 0.0 0.0 42.0 'no' 'no' 92.0]
 [1.0 0.0 0.0 74.0 'yes' 'yes' 75.0]
 [1.0 0.0 0.0 62.0 'yes' 'yes' 68.0]
 [0.0 1.0 0.0 24.0 'no' 'no' 92.0]
 [0.0 1.0 0.0 48.0 'no' 'yes' 93.0]
 [1.0 0.0 0.0 58.0 'no' 'no' 70.0]
 [0.0 1.0 0.0 45.130434782608695 'yes' 'no' 90.0]
 [0.0 1.0 0.0 15.0 'no' 'no' 92.0]
 [0.0 0.0 1.0 70.0 'no' 'yes' 88.0]
 [1.0 0.0 0.0 52.0 'yes' 'yes' 80.0]
 [1.0 0.0 0.0 60.0 'yes' 'yes' 68.0]
 [1.0 0.0 0.0 54.0 'yes' 'yes' 70.0]
 [0.0 0.0 1.0 29.0 'no' 'no' 93.0]
 [1.0 0.0 0.0 78.0 'yes' 'yes' 71.0]
 [1.0 0.0 0.0 36.0 'yes' 'no' 90.0]
 [0.0 1.0 0.0 30.0 'yes' 'no' 86.0]
 [1.0 0.0 0.0 50.0 'yes' 'yes' 77.0]
 [0.0 0.0 1.0 18.0 'no' 'no' 93.0]
 [1.0 0.0 0.0 69.0 'no' 'yes' 53.0]
 [0.0 0.0 1.0 10.0 'no' 'no' 97.0]
 [1.0 0.0 0.0 26.0 'no' 'no' 94.0]
 [0.0 1.0 0.0 18.0 'no' 'no' 66.0]
 [1.0 0.0 0.0 62.0 'yes' 'yes' 69.0]
 [0.0 1.0 0.0 13.0 'no' 'no' 93.0]
 [1.0 0.0 0.0 4

In [ ]:
print(Y_train)

[1 0 1 0 1 1 0 0 1 0 0 0 1 1 1 0 1 0 0 1 0 1 0 0 1 1 0 0 1 1 1 0 0 1 0 1 0
 1 1 0 0 0 1 1 0 1 1 0 1 0 0 0 1 0 0 1]


# Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train[:,6:]=sc.fit_transform(X_train[:,6:])
X_test[:,6:]=sc.transform(X_test[:,6:])

In [ ]:
X_train

array([[1.0, 0.0, 0.0, 86.0, 'yes', 'yes', -0.9941858494300261],
       [0.0, 1.0, 0.0, 35.0, 'no', 'yes', 0.9574354145081887],
       [1.0, 0.0, 0.0, 75.0, 'no', 'yes', -0.9012515035282064],
       [1.0, 0.0, 0.0, 42.0, 'no', 'no', 0.9574354145081887],
       [1.0, 0.0, 0.0, 74.0, 'yes', 'yes', -0.6224484658227472],
       [1.0, 0.0, 0.0, 62.0, 'yes', 'yes', -1.2729888871354853],
       [0.0, 1.0, 0.0, 24.0, 'no', 'no', 0.9574354145081887],
       [0.0, 1.0, 0.0, 48.0, 'no', 'yes', 1.0503697604100084],
       [1.0, 0.0, 0.0, 58.0, 'no', 'no', -1.087120195331846],
       [0.0, 1.0, 0.0, 45.130434782608695, 'yes', 'no',
        0.7715667227045492],
       [0.0, 1.0, 0.0, 15.0, 'no', 'no', 0.9574354145081887],
       [0.0, 0.0, 1.0, 70.0, 'no', 'yes', 0.5856980309009097],
       [1.0, 0.0, 0.0, 52.0, 'yes', 'yes', -0.15777673631364833],
       [1.0, 0.0, 0.0, 60.0, 'yes', 'yes', -1.2729888871354853],
       [1.0, 0.0, 0.0, 54.0, 'yes', 'yes', -1.087120195331846],
       [0.0, 0.0, 1.0, 2

In [ ]:
X_test

array([[0.0, 0.0, 1.0, 25.0, 'no', 'yes', 0.3998293390972702],
       [0.0, 0.0, 1.0, 10.0, 'no', 'no', 1.4221071440172874],
       [1.0, 0.0, 0.0, 68.0, 'yes', 'no', -1.3659232330373052],
       [0.0, 1.0, 0.0, 13.0, 'no', 'no', 1.143304106311828],
       [1.0, 0.0, 0.0, 59.0, 'yes', 'no', -1.2729888871354853],
       [0.0, 0.0, 1.0, 28.0, 'no', 'no', 1.607975835820927],
       [0.0, 0.0, 1.0, 20.0, 'no', 'no', 1.0503697604100084],
       [1.0, 0.0, 0.0, 46.0, 'yes', 'no', 0.864501068606369],
       [1.0, 0.0, 0.0, 53.0, 'yes', 'no', -2.4811353838591423],
       [0.0, 0.0, 1.0, 16.0, 'no', 'no', 0.9574354145081887],
       [1.0, 0.0, 0.0, 38.0, 'no', 'no', -0.6224484658227472],
       [0.0, 0.0, 1.0, 19.0, 'no', 'no', 0.9574354145081887],
       [1.0, 0.0, 0.0, 94.0, 'yes', 'yes', -1.6447262707427643],
       [0.0, 1.0, 0.0, 12.0, 'no', 'no', 1.4221071440172874]],
      dtype=object)